apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: dialogfordeler-alerts
  namespace: default
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#syfo-alarm'
      prependText: '<!here> | '
  alerts:
    - alert: dialogfordeler is down
      expr: up{app="dialogfordeler", job="kubernetes-pods"} == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i prod"
      action: "Trenger å sparke igang poden(e) igjen, bruk `k delete pod -n {{ $labels.kubernetes_namespace }} {{ $labels.kubernetes_pod_name }}` på alle poder som er nede"
      severity: danger
    - alert: dialogfordeler jms pool exception
      expr: rate(dialogfordeler_jms_error_pool{app="dialogfordeler"}[5m]) > 0
      for: 1m
      description: "App {{ $labels.app }} får ExhautedPoolException fra Atomikos/JMS i prod"
      action: "Trenger å sparke igang poden(e) igjen, bruk `k delete pod -n {{ $labels.kubernetes_namespace }} {{ $labels.kubernetes_pod_name }}` på alle poder som er nede"
      severity: danger
    - alert: dialogfordeler jms general exception
      expr: rate(dialogfordeler_jms_error_general{app="dialogfordeler"}[5m]) > 0
      for: 1m
      description:  "App {{ $labels.app }} får feil ved lesing fra MQ i prod"
      action: "Bør ta en titt på logger i Kibana for å se om noe bør fikses"
      severity: warning
