apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: dialogfordeler-alerts
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#veden-alerts'
      prependText: '<!here> | '
  alerts:
    - alert: dialogfordeler is down
      expr: up{app="dialogfordeler", job="kubernetes-pods"} == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "Trenger å sparke igang poden(e) igjen, bruk `k delete pod -n {{ $labels.kubernetes_namespace }} {{ $labels.kubernetes_pod_name }}` på alle poder som er nede"
      severity: danger