apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dialogfordeler
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://dialogfordeler.nais.adeo.no"
  vault:
    enabled: true
    paths:
      - kvPath: "/oracle/data/prod/creds/dialogfordeler-user"
        mountPath: "/secrets/dialogfordelerdb/credentials"
      - kvPath: "/oracle/data/prod/config/dialogfordeler"
        mountPath: "/secrets/dialogfordelerdb/config"
      - kvPath: "/serviceuser/data/prod/srvdialogfordeler"
        mountPath: "/secrets/serviceuser/dialogfordeler"
      - kvPath: "/kv/prod/fss/dialogfordeler/default"
        mountPath: "/var/run/secrets/nais.io/vault"
  env:
    - name: APP_NAME
      value: "dialogfordeler"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: DIALOGFORDELER_DIALOGMELDINGER_QUEUENAME
      value: QA.P_DIALOGFORDELER.DIALOGMELDINGER
    - name: DIALOGFORDELER_DIALOGMELDINGER_QUEUEMANAGER
      value: mq://a01apvl062.adeo.no:1414/MPLSC03
    - name: DIALOGFORDELER_CHANNEL_QUEUEMANAGER
      value: mq://a01apvl062.adeo.no:1414/MPLSC03
    - name: DIALOGFORDELER_CHANNEL_NAME
      value: P_DIALOGFORDELER
    - name: MOTTAK_QUEUE_EIA2_MELDINGER_QUEUENAME
      value: QA.P414.FS06_EIA_MELDINGER
    - name: MOTTAK_QUEUE_UTSENDING_QUEUENAME
      value: QA.P414.IU03_UTSENDING
    - name: MOTTAK_QUEUE_EBREV_KVITTERING_QUEUENAME
      value: QA.P414.IU03_EBREV_KVITTERING
    - name: MQGATEWAY03_HOSTNAME
      value: a01apvl062.adeo.no
    - name: MQGATEWAY03_PORT
      value: '1414'
    - name: MQGATEWAY03_NAME
      value: MPLSC03
    - name: ABAC_URL
      value: https://wasapp.adeo.no/asm-pdp/authorize
    - name: security-token-service-jwks
    - name: SECURITY_TOKEN_SERVICE_JWKS_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/jwks
    - name: SECURITY_TOKEN_SERVICE_ISSUER_URL
      value: https://security-token-service.nais.adeo.no
    - name: MOTTAK_QUEUE_PADM2_MELDINGER_QUEUENAME
      value: QA.P_PADM.INPUT
