apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dialogfordeler
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 384Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://dialogfordeler.nais.preprod.local"
  vault:
    enabled: true
    paths:
      - kvPath: "/oracle/data/dev/creds/dialogfordeler_q1-user"
        mountPath: "/secrets/dialogfordelerdb/credentials"
      - kvPath: "/oracle/data/dev/config/dialogfordeler_q1"
        mountPath: "/secrets/dialogfordelerdb/config"
      - kvPath: "/serviceuser/data/dev/srvdialogfordeler"
        mountPath: "/secrets/serviceuser/dialogfordeler"
      - kvPath: "/kv/preprod/fss/dialogfordeler/default"
        mountPath: "/var/run/secrets/nais.io/vault"
  env:
    - name: APP_NAME
      value: "dialogfordeler"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: DIALOGFORDELER_DIALOGMELDINGER_QUEUENAME
      value: QA.Q1_DIALOGFORDELER.DIALOGMELDINGER
    - name: DIALOGFORDELER_DIALOGMELDINGER_QUEUEMANAGER
      value: mq://b27apvl173.preprod.local:1413/MQ1LSC03
    - name: DIALOGFORDELER_CHANNEL_QUEUEMANAGER
      value: mq://b27apvl173.preprod.local:1413/MQ1LSC03
    - name: DIALOGFORDELER_CHANNEL_NAME
      value: Q1_DIALOGFORDELER
    - name: MOTTAK_QUEUE_EIA2_MELDINGER_QUEUENAME
      value: QA.Q414.FS06_EIA_MELDINGER
    - name: MOTTAK_QUEUE_UTSENDING_QUEUENAME
      value: QA.Q414.IU03_UTSENDING
    - name: MOTTAK_QUEUE_EBREV_KVITTERING_QUEUENAME
      value: QA.Q414.IU03_EBREV_KVITTERING
    - name: MQGATEWAY03_HOSTNAME
      value: b27apvl173.preprod.local
    - name: MQGATEWAY03_PORT
      value: '1413'
    - name: MQGATEWAY03_NAME
      value: MQ1LSC03
    - name: ABAC_URL
      value: https://wasapp-q1.adeo.no/asm-pdp/authorize
    - name: security-token-service-jwks
    - name: SECURITY_TOKEN_SERVICE_JWKS_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/jwks
    - name: SECURITY_TOKEN_SERVICE_ISSUER_URL
      value: https://security-token-service.nais.preprod.local
    - name: MOTTAK_QUEUE_PADM2_MELDINGER_QUEUENAME
      value: QA.Q1_PADM.INPUT
    - name: TOGGLE_LEGG_MELDINGER_PA_KO
      value: "true"
