--ROLLBACK
----------
-- DROP TABLE MELDING_LOGG;
-- DROP SEQUENCE MELDING_LOGG_ID_SEQ;
----------
--ROLLBACK

CREATE SEQUENCE MELDING_LOGG_ID_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE MELDING_LOGG (
  id         NUMBER       NOT NULL PRIMARY KEY,
  melding_id NUMBER       NOT NULL,
  type       VARCHAR(255) NOT NULL,
  melding    CLOB         NOT NULL,
  registrert TIMESTAMP    NOT NULL,
  CONSTRAINT ML_M_FK FOREIGN KEY (melding_id) REFERENCES MELDING (id)
);